apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnapp-server
  labels:
    app: cnapp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnapp-server
  template:
    metadata:
      labels:
        app: cnapp-server
    spec:
      containers:
      - name: server
        image: ckstj8027/cnapp-server:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cnapp-server
spec:
  type: NodePort
  selector:
    app: cnapp-server
  ports:
    - port: 8080
      targetPort: 8080
      # nodePort: 30080 # 자동 할당되도록 주석 처리
